import Head from 'next/head'

export default function Home() {
	return (
		<>
			<Head>
				<title>SazzadTanim's App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
			</Head>
			<h1 className='bg-red-400'>Hello everyone</h1>
		</>
	)
}
